// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RazorProject.Models;

public partial class Department
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(25)]
    public string Name { get; set; }

    public int Capacity { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}