// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RazorProject.Models;

[Index("DeptId", Name = "IX_Students_DeptId")]
public partial class Student
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(25)]
    public string Name { get; set; }

    public int Grade { get; set; }

    public int DeptId { get; set; }

    [Required]
    public string Email { get; set; }

    [Required]
    public string Password { get; set; }

    [ForeignKey("DeptId")]
    [InverseProperty("Students")]
    public virtual Department Dept { get; set; }
}